<a href="https://colab.research.google.com/github/Requenamar3/Machine-Learning/blob/main/CAP4631C_Assigment1_Spring25_Questions_Group_1_Anays_Garcia%2C_Martha_Requena.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 1. CAP 4631C. Spring 2025

### Instructions:

Download the file "radiation_clean.csv" from Canvas (especifically from the Assignment 1 section). Open a python notebook in Colab and read this file as a data frame in this notebook (as we have done in class with other csv files). Call this data frame __df_assig1__

The radiation_clean dataset is part of EPA's RadNet Database. It contains the near-real-time environmental radiation data from fixed and deployable air monitors in different locations in the US. It contains data about the level of several radioactive substances in different locations.

In [45]:
import numpy as np
import pandas as pd

In [46]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [47]:
df_assig1= "/content/drive/MyDrive/Colab Notebooks/Machine learning/Data set/radiation_clean.csv"

In [48]:
df_assig1 = pd.read_csv(df_assig1)

__AFTER__ you read the csv file as a data frame, take a look at __df_assig1__ by running the following code cell:

In [49]:
df_assig1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 606 entries, 0 to 605
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   State           606 non-null    object 
 1   Location        606 non-null    object 
 2   Date Posted     606 non-null    object 
 3   Date Collected  606 non-null    object 
 4   Sample Type     606 non-null    object 
 5   Unit            606 non-null    object 
 6   Ba-140          605 non-null    float64
 7   Co-60           605 non-null    float64
 8   Cs-134          606 non-null    int64  
 9   Cs-136          506 non-null    float64
 10  Cs-137          606 non-null    int64  
 11  I-131           606 non-null    int64  
 12  I-132           606 non-null    int64  
 13  I-133           605 non-null    float64
 14  Te-129          506 non-null    float64
 15  Te-129m         506 non-null    float64
 16  Te-132          606 non-null    int64  
 17  Ba-140.1        0 non-null      flo

__Question 1__ (8 points): Create a Numpy array called _i131_data_ with the data from the column _I-131_ in __df_assig1__.

Note: I-131 (i.e., Iodine-131) is one of many radiactive substances.

Hint: Use the same method we used in class to read the PRCP column from the rain dataset into a NumPy array.

In [50]:
# Extract the I-131 column from df_assig1 and convert it to a NumPy array
i131_data = df_assig1['I-131'].to_numpy()

# Display the first few elements of the array (optional)
print(i131_data)

[  0   0   0   0   0   0   0   0   0   0   1   1   0   1   2   0   0   1
   0   1   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   1   1   0   0   1   1   0   0   0   0   0   0   0   0   0   2
   3   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0
   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   1
   0   0   0   0   0   0   0   0   0   0   1   1   0   1   1   0   0   0
   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0
   0   0   0   0   1   0   1   0   0   1   0   0   0   0   0   0   0   0
   0   1   1   0   0   0   0   0   0   0   0   0   0   0   1   1   0   1
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   

__Question 2__ (8 points): Return the first, sixth, and twelfth elements of i131_data. __Write only one line of code__ to answer this question.

In [51]:
# Answer question 2 here
i131_data[[0, 5, 11]]


array([0, 0, 1])

__Question 3__ (8 points): Return the last five elements of i131_data.

Spring 24: __Write only one line of code__ to answer this question.

In [52]:
# Answer question 3 here
i131_data[-5:]


array([6, 0, 0, 0, 0])

__Question 4__ (8 points): Return how many times the value of i131_data is between 2 and 4 (both numbers included).

__Write only one line of code__ to answer this question.

In [53]:
# Answer question 4 here
np.sum((i131_data >= 2) & (i131_data <= 4))


25

__Question 5__ (8 points): Return how many times the value of i131_data is either zero or 1. To answer this question, you __CANNOT__ use the symbol < in your answer (the _less than_ symbol). You __must__ answer it without using this symbol.

In [54]:
# Answer question 5 here
np.sum((i131_data == 0) | (i131_data == 1))

515

__Question 6__ (8 points): Return the names of the States where i131_data has been above 2. Use ONLY ONE line of code.

Hint: It is ok if your output shows the same State repeated many times.

In [55]:
# Answer question 6 here
df_assig1.loc[i131_data > 2, 'State']


54     AK
408    HI
411    MO
415    AR
417    CA
       ..
574    CO
579    CT
585    MI
598    WA
601    CA
Name: State, Length: 82, dtype: object

__Question 7__ (8 points): Return how many times i131_data has a value of zero in California.

Hint: California is recorded as CA in the State colum.

In [56]:
# Answer question 7 here
np.sum((i131_data == 0) & (df_assig1['State'] == 'CA'))


31

__Question 8__ (8 points): Write a print statement that returns this message: _The highest registered value of I-131 is:_ FILL IN THE BLANK

where, FILL IN THE BLANK is the actual highest registered value of i131_data.

In [57]:
highest_value = i131_data.max()
print(f"The highest registered value of I-131 is: {highest_value}")

The highest registered value of I-131 is: 390


__Question 9__ (8 points): Run the following code cell to create an array called q9_array.

In [58]:
q9_array = np.array ([13, 8, 3, 6, 8, 17, 2, 5, 10])

9a) Create a new array called q9_array_sorted that contains the sorted values of q9_array.

In [59]:

q9_array_sorted = np.array(sorted(q9_array))
q9_array_sorted


array([ 2,  3,  5,  6,  8,  8, 10, 13, 17])

9b) Create a new array called q9_array_2dim that re-arranges the values of q9_array in a two-dimensional squared array (squared= with the same number of rows and columns).

In [60]:

total_elements = len(q9_array)
dimension_size = int(total_elements**0.5)
q9_array_2dim = q9_array.reshape(dimension_size, dimension_size)
print(q9_array_2dim)

[[13  8  3]
 [ 6  8 17]
 [ 2  5 10]]


__Question 10__ (8 points): Use NumPy methods to generate the following arrays:

10 a) Generate an array with the numbers from 96 to 0, decreasing in steps of 8 (i.e., 96, 88, 80, ...., 0). Call this array a1.

10 b) Generate an array with the number 2 repeated as many times as the size of array a1. Call this array a2.

10 c) Add the arrays created in a) and b) and save the results in a3. Return the values of a3 (i.e., print the values of a3).

Note: To answer question 10 and create the arrays requested in a, b, and c, you __CANNOT__ enter the values of the arrays manually. You __must__ use the NumPy methods we learned in class to create them.

In [61]:

a1 = np.arange(96, -1, -8)
print(a1)

[96 88 80 72 64 56 48 40 32 24 16  8  0]


In [62]:
size_of_a1 = len(a1)
a2 = np.full(size_of_a1, 2)

print(a2)

[2 2 2 2 2 2 2 2 2 2 2 2 2]


In [63]:
a3=a1+a2
print(a3)

[98 90 82 74 66 58 50 42 34 26 18 10  2]


__Question 11__ (5 points): Return how many observations were taken at each State. __Write only one line of code__ to answer this question.

In [64]:

df_assig1['State'] = df_assig1['State'].str.strip().str.title()
state_counts = df_assig1['State'].value_counts()
print("Occurrences of each state, ordered by name:")
print(state_counts)

Occurrences of each state, ordered by name:
State
Ak      71
Tn      56
Hi      49
Ca      42
Id      29
Guam    24
Nv      23
Ny      22
Al      20
Wa      19
Oh      19
Cnmi    19
Pa      16
Nc      12
Ct      11
Fl      11
Ar      10
Nh      10
Ma      10
Mi       9
Ks       9
Ut       9
Mn       8
Ga       8
Sc       8
Tx       7
Va       6
Or       6
Md       6
Co       6
Nj       5
De       4
Ms       4
Mo       4
Ia       4
Nm       4
Il       4
Az       3
Ok       2
Ri       2
Wi       2
Nd       2
Ne       2
Mt       2
Wv       2
Ky       2
La       2
Vt       1
Name: count, dtype: int64


__Question 12__ (5 points): Return the __df_assig1__ data frame sorted by the 'Date Collected'. Show the latest collected observations first. __Write only one line of code__ to answer this question.

In [65]:
sorted_df = df_assig1.sort_values(by='Date Collected', ascending=False)
print(sorted_df)

    State     Location Date Posted Date Collected     Sample Type    Unit  \
577    Pa   Harrisburg  2011-05-24     2011-04-30  Precipitation    pCi/l   
570    Nc    Charlotte  2011-05-24     2011-04-29  Precipitation    pCi/l   
584    Tn    Knoxville  2011-05-24     2011-04-29  Precipitation    pCi/l   
568    Ma       Boston  2011-05-24     2011-04-29  Precipitation    pCi/l   
599    Oh  Painesville  2011-05-24     2011-04-29  Precipitation    pCi/l   
..    ...          ...         ...            ...             ...     ...   
539    Oh  Painesville  2011-04-04     2011-03-15   Precipitation   pCi/l   
510    Tn    Nashville  2011-04-13     2011-03-15   Precipitation   pCi/l   
213    Ca    Riverside  2011-03-30     2011-03-15      Air Filter  pCi/m3   
543    Ca     Richmond  2011-04-04     2011-03-15   Precipitation   pCi/l   
24     Ca      Anaheim  2011-03-30     2011-03-11      Air Filter  pCi/m3   

     Ba-140  Co-60  Cs-134  Cs-136  Cs-137  I-131  I-132  I-133  Te-129  \


__Question 13__ (5 points): Return the __df_assig1__ data frame only showing the samples taken in Miami. Miami is one of the values from the column 'Location'. __Write only one line of code__ to answer this question.

In [66]:
miami_samples = df_assig1[df_assig1['Location'] == 'Miami']
print(miami_samples)


    State Location Date Posted Date Collected     Sample Type   Unit  Ba-140  \
312    Fl    Miami  2011-04-08     2011-03-29  Drinking Water  pCi/l     0.0   

     Co-60  Cs-134  Cs-136  Cs-137  I-131  I-132  I-133  Te-129  Te-129m  \
312    0.0       0     0.0       0      0      0    0.0     0.0      0.0   

     Te-132  Ba-140.1  
312       0       NaN  


__Question 14__ (5 points): Return the average concentration of 'I-131' found on each state. __Write only one line of code__ to answer this question.

In [67]:
average_concentration = df_assig1.groupby('State')['I-131'].mean()
print(average_concentration)


State
Ak       0.154930
Al       1.050000
Ar       5.900000
Az       1.000000
Ca       7.119048
Cnmi     0.105263
Co       8.333333
Ct       5.454545
De       0.000000
Fl      15.636364
Ga       2.125000
Guam     0.041667
Hi       0.591837
Ia       0.000000
Id      23.068966
Il       0.000000
Ks      24.444444
Ky       0.000000
La       0.000000
Ma      14.400000
Md       0.000000
Mi       2.777778
Mn       7.125000
Mo       0.750000
Ms       0.000000
Mt       0.000000
Nc       7.500000
Nd       0.000000
Ne       0.000000
Nh       7.100000
Nj       0.000000
Nm       0.000000
Nv       0.173913
Ny       3.227273
Oh       2.789474
Ok       0.000000
Or      14.500000
Pa       0.750000
Ri       0.000000
Sc       0.000000
Tn       7.535714
Tx       0.000000
Ut      24.444444
Va       1.500000
Vt       0.000000
Wa      10.368421
Wi       0.000000
Wv       0.000000
Name: I-131, dtype: float64
